apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rooms-service
  name: rooms-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rooms-service
  template:
    metadata:
      labels:
        app: rooms-service
    spec:
      containers:
        - name: rooms-service
          image: rooms-service
          livenessProbe:
            httpGet:
              path: /live
              port: 3001
          readinessProbe:
            httpGet:
              path: /ready
              port: 3001
          envFrom:
            - configMapRef:
                name: base-config
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: MONGO_URI
              value: mongodb://rooms-mongo-mongodb.default.svc.cluster.local:27017
          resources:
            requests:
              cpu: 40m
            limits:
              cpu: 70m
      restartPolicy: Always
