apiVersion: v1
kind: Service
metadata:
  name: rooms-service
spec:
  selector:
    app: rooms-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP      # Internal cluster IP
