apiVersion: v1
kind: Service
metadata:
  name: cards-mongo-mongodb
spec:
  selector:
    app: cards-mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  clusterIP: None  # This makes it a headless service
