apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: clients-service
  name: clients-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clients-service
  template:
    metadata:
      labels:
        app: clients-service
    spec:
      containers:
        - name: clients-service
          image: clients-service
          volumeMounts:
            - name: firebase-auth
              mountPath: /secrets
              readOnly: true
          livenessProbe:
            httpGet:
              path: /live
              port: 3001
          readinessProbe:
            httpGet:
              path: /ready
              port: 3001
          envFrom:
            - configMapRef:
                name: base-config
          env:
            - name: PORT
              value: "80"
            - name: MONGO_URI
              value: mongodb://clients-mongo-mongodb.default.svc.cluster.local:27017
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-auth
                  key: jwtSecret
            - name: GCP_SERVICE_ACCOUNT_PATH
              value: /secrets/auth.json
          resources:
            requests:
              cpu: 40m
            limits:
              cpu: 70m
      volumes:
      - name: firebase-auth
        secret:
          secretName: firebase-auth
      restartPolicy: Always
