apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cards-service
  name: cards-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cards-service
  template:
    metadata:
      labels:
        app: cards-service
    spec:
      containers:
        - name: cards-service
          image: cards-service
          livenessProbe:
            httpGet:
              path: /live
              port: 3001
          readinessProbe:
            httpGet:
              path: /ready
              port: 3001
          envFrom:
            - configMapRef:
                name: base-config
          env:
            - name: PORT
              value: "80"
            - name: MONGO_URI
              value: mongodb://cards-mongo-mongodb.default.svc.cluster.local:27017/local
          resources:
            requests:
              cpu: 40m
            limits:
              cpu: 70m
      restartPolicy: Always
